// vue-client/src/components/record/log-modal.vue
<template>
    <div
        class="modal fade"
        id="logModal"
        tabindex="-1"
        role="dialog"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">{{message}}</h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
                @click="close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Do you want to replace old weight?
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
                @click="close"
              >
                No
              </button>
              <button 
              type="button" @click="submit" class="btn btn-primary">
                Yes
              </button>
            </div>
          </div>
        </div>
      </div>
</template>


<script>
export default {
    name:'modal',
    props: {
        closeFunc: Function,
        updateFunc: Function,
        message: String
        },
    methods: {
        submit: function(e) {
            this.updateFunc(e);
        },
        close: function() {
            this.closeFunc();
        }
    }
}
</script>

<style scoped>
button {
    margin: 0px 5px;
}
</style>

// react-client/src/components/Record/LogModal.js
import React, { Component } from "react";
import PropTypes from 'prop-types';

export class LogModal extends Component {
  constructor(props) {
    super(props);
    this.close = this.close.bind(this);
  }
  submit(e) {
    this.props.closeFunc(e);
  }
  close() {
    this.props.resetFunc();
  }
  render() {
    const buttonStyle ={
      margin: '0px 5px'
    }
    return (
      <div
        className="modal fade"
        id="logModal"
        tabindex="-1"
        role="dialog"
        aria-hidden="true"
      >
        <div className="modal-dialog modal-dialog-centered" role="document">
          <div className="modal-content">
            <div className="modal-header">
              <h5 className="modal-title">{this.props.message}</h5>
              <button
                type="button"
                className="close"
                data-dismiss="modal"
                aria-label="Close"
                onClick={this.close}
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div className="modal-body">
              Do you want to replace old weight?
              <button
              style={buttonStyle}
                type="button"
                className="btn btn-secondary"
                data-dismiss="modal"
                onClick={this.close}
              >
                No
              </button>
              <button 
              style={buttonStyle}
              type="button" onClick={this.submit.bind(this)} className="btn btn-primary">
                Yes
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

}

LogModal.propTypes = {
  updateFunc: PropTypes.func,
  resetFunc: PropTypes.func
}
